In [24]:
import pandas as pd
from sklearn import preprocessing

df = pd.read_csv("../data/SCC403CWWeatherData.txt")

# Assign Column Names
df.columns = ['temp.min', 'temp.max', 'temp.mean',
              'hum.min', 'hum.max', 'hum.mean',
              'press.min', 'press.max', 'press.mean',
              'precipipitation', 'snowfall', 'sunshine',
              'gust.min', 'gust.max', 'gust.mean',
              'speed.min', 'speed.max', 'speed.mean']

df.describe()

,temp.min,temp.max,temp.mean,hum.min,hum.max,hum.mean,press.min,press.max,press.mean,precipipitation,snowfall,sunshine,gust.min,gust.max,gust.mean,speed.min,speed.max,speed.mean
count,1762.000000,1762.000000,1762.000000,1762.000000,1762.000000,1762.000000,1762.000000,1762.000000,1762.000000,1762.000000,1762.000000,1762.000000,1762.000000,1762.000000,1762.000000,1762.000000,1762.000000,1762.000000
mean,8.739138,16.778849,12.716937,54.088536,86.999432,71.036630,1014.691827,1020.365607,1017.577424,1.503632,0.068053,399.195825,7.237593,30.468217,17.570124,2.933495,14.861291,8.419848
std,7.805901,9.650489,8.791033,12.952457,7.891405,10.013695,8.850681,8.016272,8.284536,3.497564,0.514078,294.742242,8.223633,16.495244,11.507308,3.471646,7.872767,5.206912
min,-12.519471,-4.389471,-7.628221,19.000000,53.000000,38.333332,976.100000,981.400000,978.450000,0.000000,0.000000,0.000000,0.000000,4.320000,2.715000,0.000000,2.881557,1.495064
25%,1.695529,8.200529,4.687821,44.000000,82.000000,63.510417,1010.300000,1015.900000,1013.231325,0.000000,0.000000,123.724200,2.160000,19.080000,9.757499,0.842431,9.304952,4.871309
50%,10.230529,17.400530,14.633654,54.000000,88.000000,72.000000,1014.600000,1019.500000,1016.956170,0.000000,0.000000,387.787200,4.320000,26.280000,14.145001,1.864800,12.988194,6.941605
75%,15.530529,25.190529,20.433550,64.000000,93.000000,78.750000,1019.300000,1024.400000,1021.761427,1.200000,0.000000,619.203330,8.910000,37.440000,21.678751,3.729600,18.398964,10.111403
max,25.820530,36.700527,30.425112,93.000000,100.000000,95.250000,1043.600000,1049.900000,1047.095800,37.399994,13.860001,962.283300,57.960000,133.200000,90.749990,26.673279,59.192370,36.360706

In [28]:
## PRE-PROCESSING

# Check for missing values
df.isna().sum() # there are none 

# Scale all columns
dfscaled = preprocessing.scale(df)

# Show mean and deviance
dfscaled.mean(axis=0)
dfscaled.std(axis=0)

# SPLIT DATASET

# Remove those that have snow 
mask = df['snowfall'] > 0
df_snowing = df[mask]
df1 = df[~mask]

# Remove those that have rain
mask = df['precipipitation'] > 0
df_raining = df[mask]
df1 = df[~mask]

# Drop non-required columns
df1 = df1.drop(['precipipitation', 'snowfall'], axis=1)

df1.head()

,temp.min,temp.max,temp.mean,hum.min,hum.max,hum.mean,press.min,press.max,press.mean,sunshine,gust.min,gust.max,gust.mean,speed.min,speed.max,speed.mean
2,10.450529,24.980530,17.309278,54,92,77.625000,1015.9,1018.7,1017.26250,881.24710,2.16,20.160000,9.480000,0.799200,11.483046,4.690738
3,12.350529,25.610529,19.881780,47,88,66.583336,1015.7,1020.7,1018.18353,951.56665,0.72,15.840000,5.565001,0.376747,6.443357,3.311275
8,16.920528,30.720530,22.644693,39,97,73.458336,1001.4,1005.7,1003.80835,531.93730,1.44,24.119999,12.209999,1.864800,15.137991,6.780077
9,16.450530,24.380530,20.846363,61,97,76.208336,1006.2,1010.7,1009.32916,597.04004,1.08,41.039997,9.480000,0.532800,20.540459,4.708371
20,8.010529,18.590528,13.726363,55,93,74.875000,1020.6,1022.3,1021.40410,597.08014,1.08,15.480001,8.445000,0.842431,9.549613,5.480354

In [25]:
# Remove those that have rain
mask = df1['temp.mean'] >= 12.716937
df_hot = df1[mask]
df_cold = df1[~mask]

df_hot.head()
#print(len(df_hot.index))

501

In [26]:
df_cold.head()
print(len(df_cold.index))

443

In [29]:
df_raining.head()
print(len(df_raining.index))

818

In [30]:
df_snowing.head()
print(len(df_snowing.index))

111